
workflows:
  android-workflow:
    name: Native Android Signed Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
    environment:
      vars:
        # 1. ЗАМЕНЕТЕ С ВАШАТА ПАРОЛА:
        MY_PASS: "904710563"
        # 2. ЗАМЕНЕТЕ С ВАШИЯ ALIAS (ако е различен):
        MY_ALIAS: "mykey"
    scripts:
      - name: Generate Gradle Wrapper
        script: |
          gradle wrapper
      - name: Create Temporary Keystore
        script: |
          # Сървърът сам ще си генерира ключ в движение, за да не се налага да го качвате
          keytool -genkey -v -keystore app/local.keystore -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias "$MY_ALIAS" -storepass "$MY_PASS" -keypass "$MY_PASS" -dname "CN=Android, O=AI, C=BG"
      - name: Set Up Code Signing
        script: |
          echo "StorePassword=$MY_PASS" >> app/signing.properties
          echo "KeyPassword=$MY_PASS" >> app/signing.properties
          echo "KeyAlias=$MY_ALIAS" >> app/signing.properties
          echo "StoreFile=local.keystore" >> app/signing.properties
      - name: Build Android Release APK
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
